# Generated by Django 3.1.2 on 2021-02-18 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('code', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('amount', models.IntegerField()),
                ('unit', models.CharField(default='個', max_length=5)),
                ('photo', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Squad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('id_code', models.CharField(max_length=10, unique=True)),
                ('squad', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='workers', to='mainApp.squad')),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('location', models.CharField(blank=True, max_length=30, null=True)),
                ('products', models.ManyToManyField(related_name='ware_houses', to='mainApp.Product')),
                ('squad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ware_houses', to='mainApp.squad')),
            ],
        ),
        migrations.CreateModel(
            name='GetProductSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('products', models.ManyToManyField(related_name='get_product_sheets', to='mainApp.Product')),
                ('squad', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='get_product_sheets', to='mainApp.squad')),
            ],
        ),
        migrations.CreateModel(
            name='CompletedProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('date', models.DateField()),
                ('get_product_sheet', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainApp.getproductsheet')),
            ],
        ),
        migrations.CreateModel(
            name='BlockedProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('date', models.DateField()),
                ('get_product_sheet', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainApp.getproductsheet')),
            ],
        ),
    ]
