# Generated by Django 3.1.2 on 2021-02-18 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_auto_20210219_0054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blockedproject',
            name='code',
        ),
        migrations.RemoveField(
            model_name='completedproject',
            name='code',
        ),
        migrations.RemoveField(
            model_name='getproductsheet',
            name='products',
        ),
        migrations.RemoveField(
            model_name='product',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='warehouse',
        ),
        migrations.AddField(
            model_name='getproductsheet',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='blockedproject',
            name='get_product_sheet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainApp.getproductsheet'),
        ),
        migrations.AlterField(
            model_name='completedproject',
            name='get_product_sheet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainApp.getproductsheet'),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(default='無', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('get_product_sheet', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='products', to='mainApp.getproductsheet')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='products', to='mainApp.warehouse')),
            ],
        ),
    ]
