# Generated by Django 3.1.2 on 2021-02-19 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0010_auto_20210219_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='static/'),
        ),
    ]
