# Generated by Django 3.1.2 on 2021-02-19 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0013_auto_20210219_1900'),
    ]

    operations = [
        migrations.CreateModel(
            name='GetProductSheetProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UseProductSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('squad', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='use_product_sheets', to='mainApp.squad')),
            ],
        ),
        migrations.CreateModel(
            name='UseProductSheetProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=30, unique=True)),
                ('date', models.DateField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='work_sheets', to='mainApp.project')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='work_sheets', to='mainApp.region')),
                ('squad', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='work_sheets', to='mainApp.squad')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='work_sheets', to='mainApp.status')),
                ('type1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='work_sheets', to='mainApp.type1')),
                ('type2', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='work_sheets', to='mainApp.type2')),
            ],
        ),
        migrations.CreateModel(
            name='WorkSheetProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='completedproject',
            name='get_product_sheet',
        ),
        migrations.RemoveField(
            model_name='products',
            name='get_product_sheet',
        ),
        migrations.RemoveField(
            model_name='products',
            name='warehouse',
        ),
        migrations.RemoveField(
            model_name='getproductsheet',
            name='code',
        ),
        migrations.RemoveField(
            model_name='getproductsheet',
            name='is_blocked',
        ),
        migrations.RemoveField(
            model_name='getproductsheet',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='getproductsheet',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='product',
            name='photo',
        ),
        migrations.DeleteModel(
            name='BlockedProject',
        ),
        migrations.DeleteModel(
            name='CompletedProject',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
        migrations.AddField(
            model_name='worksheetproducts',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='work_sheet_productss', to='mainApp.product'),
        ),
        migrations.AddField(
            model_name='worksheetproducts',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='work_sheet_productss', to='mainApp.warehouse'),
        ),
        migrations.AddField(
            model_name='worksheetproducts',
            name='work_sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='work_sheet_productss', to='mainApp.worksheet'),
        ),
        migrations.AddField(
            model_name='useproductsheetproducts',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='use_product_sheet_productss', to='mainApp.product'),
        ),
        migrations.AddField(
            model_name='useproductsheetproducts',
            name='use_product_sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='use_product_sheet_productss', to='mainApp.useproductsheet'),
        ),
        migrations.AddField(
            model_name='useproductsheetproducts',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='use_product_sheet_productss', to='mainApp.warehouse'),
        ),
        migrations.AddField(
            model_name='getproductsheetproducts',
            name='get_product_sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='get_product_sheet_productss', to='mainApp.getproductsheet'),
        ),
        migrations.AddField(
            model_name='getproductsheetproducts',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='get_product_sheet_productss', to='mainApp.product'),
        ),
        migrations.AddField(
            model_name='getproductsheetproducts',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='get_product_sheet_productss', to='mainApp.warehouse'),
        ),
    ]
