# Generated by Django 3.1.2 on 2021-02-20 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0014_auto_20210220_0114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worksheetproducts',
            name='warehouse',
        ),
    ]
