# Generated by Django 3.1.2 on 2021-02-20 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0015_remove_worksheetproducts_warehouse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worksheetproducts',
            old_name='work_sheet',
            new_name='worksheet',
        ),
    ]
