# Generated by Django 3.1.2 on 2021-02-20 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0016_auto_20210220_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='getproductsheet',
            name='serial_number',
            field=models.CharField(default=123, max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
