# Generated by Django 3.1.2 on 2021-02-20 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0017_getproductsheet_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='squad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='mainApp.squad'),
        ),
    ]
