# Generated by Django 3.1.2 on 2021-02-20 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0018_auto_20210220_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='useproductsheet',
            name='discription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useproductsheet',
            name='status',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.DO_NOTHING, related_name='use_product_sheets', to='mainApp.status'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useproductsheet',
            name='worksheet',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.DO_NOTHING, related_name='use_product_sheets', to='mainApp.worksheet'),
            preserve_default=False,
        ),
    ]
