# Generated by Django 3.1.2 on 2021-02-20 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0019_auto_20210220_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksheet',
            name='address',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='worksheet',
            name='batch',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
