# Generated by Django 3.1.2 on 2021-02-22 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0020_auto_20210220_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useproductsheet',
            name='worksheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='use_product_sheets', to='mainApp.worksheet'),
        ),
        migrations.AlterField(
            model_name='worksheetproducts',
            name='worksheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_sheet_productss', to='mainApp.worksheet'),
        ),
    ]
