# Generated by Django 3.1.2 on 2021-02-24 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0021_auto_20210223_0341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getproductsheetproducts',
            name='get_product_sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_product_sheet_productss', to='mainApp.getproductsheet'),
        ),
        migrations.AlterField(
            model_name='getproductsheetproducts',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_product_sheet_productss', to='mainApp.warehouse'),
        ),
    ]
