# Generated by Django 3.1.2 on 2021-02-25 13:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0022_auto_20210224_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='getproductsheetproducts',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useproductsheet',
            name='point',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='useproductsheetproducts',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worksheet',
            name='point',
            field=models.IntegerField(default=0),
        ),
    ]
