# Generated by Django 3.1.2 on 2021-02-26 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0025_project_warehouse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='warehouse',
        ),
        migrations.AddField(
            model_name='warehouse',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='warehouses', to='mainApp.project'),
        ),
    ]
