# Generated by Django 3.1.7 on 2021-02-28 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0026_auto_20210226_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getproductsheet',
            name='serial_number',
            field=models.CharField(max_length=30),
        ),
    ]
