# Generated by Django 3.1.6 on 2021-03-02 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0027_auto_20210228_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='useproductsheet',
            name='warehouse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainApp.warehouse'),
            preserve_default=False,
        ),
    ]
