# Generated by Django 3.1.7 on 2021-03-07 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0030_getproductsheet_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='getproductsheet',
            name='out_warehouse',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='out_product_sheets', to='mainApp.warehouse'),
        ),
        migrations.AlterField(
            model_name='getproductsheet',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_product_sheets', to='mainApp.warehouse'),
        ),
    ]
