# Generated by Django 3.1.2 on 2021-03-21 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0031_auto_20210307_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='project',
        ),
        migrations.AddField(
            model_name='useproductsheet',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='use_product_sheets', to='mainApp.project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='getproductsheet',
            name='squad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_product_sheets', to='mainApp.squad'),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_sheets', to='mainApp.project'),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='squad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_sheets', to='mainApp.squad'),
        ),
    ]
